  extends:
    - 'airbnb-base'
  rules:
    no-console: 0
    semi: 
      - warn
      - always
    quotes:
      - warn
      - single
    import/extensions:
      - error
      - ignorePackages
      - js: always
  reportUnusedDisableDirectives: true
